# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: develop
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python==3.11.9
  - pip==23.3.1
  - pytorch==2.1.2
  - torchvision==0.16.1
  - rasterio==1.3.9 #object-level
  - numpy==1.24.3
  - tqdm==4.65.0
  - shapely==2.0.4  #make-masks
  - tensorboard==2.15.2
  # NoteBooks
  - jupyterlab==4.0.11
  - nb_conda_kernels==2.3.1
  - pip:
    - opencv-python==4.9.0.80
    - pandas==2.2.2
    - matplotlib==3.8.4
    - flake8