# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: nlrc
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python==3.11.9
  - pip==23.3.1
  - rasterio==1.3.9
  - gdal==3.8.4
  - jupyterlab==4.0.11
  - numpy==1.24.3
  - nb_conda_kernels==2.3.1
  - tqdm==4.65.0
  - humanfriendly==10.0
  - geopandas==0.14.2
  - shapely==2.0.4
  - scikit-learn==1.3.0
  - tensorboard==2.15.2
  - tensorflow==2.15.0
  - pytorch==2.1.2
  - torchvision==0.16.1
  - cudatoolkit==11.8.0
  - pip:
    - azure-storage-blob==12.19.1
    - opencv-python==4.9.0.80
    - pandas==2.2.2
    - matplotlib==3.8.4
    - scikit-image==0.23.2

