# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: develop
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python==3.11.9
  - pip==23.3.1
  - pytorch
  - tqdm
  - shapely  #make-masks
  - tensorboard
  - scikit-learn
  - pandas
  - matplotlib
  - flake8
  - numpy
  # NoteBooks
  - jupyterlab
  - nb_conda_kernels
  - pip:
    - torchvision
    - rasterio  #object-level
    - opencv-python
    - seaborn