export BASE_PATH="/home/mrtc101/Desktop/tesina/repo/main"
export SRC_PATH="${BASE_PATH}/src"
export APP_PATH="${BASE_PATH}/web_page"
export FLASK_APP="${APP_PATH}/app.py"
export WEIGTHS="${APP_PATH}/model_best.pth.tar"