hyperparameter:
  learning_rate: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
  hps_epochs: [50]
  final_epochs: [200]
  batch_size: [16]

train:
  folds: 5
  batch_workers: 0
  freeze_seg: False
  checkpoint: True
  RLROP_patience: 200 # ReduceOnPlanteu epochs patience. (Not using it in this experiment)

visual:
  num_chips_to_viz: 3
  labels_dmg: [0, 1, 2, 3, 4]
  labels_bld: [0, 1]

weights:
  weights_loss: [1, 1, 1]

preprocessing:
  custom_sampling: True
  img_num: 1250
  aug_num: 0
  cutmix: False
  disasters:
    - all
