node:
  node_name: "ivb09"
  cpu_num: 9
  partition: "multi"
  hours: 2

# Project and Experiment paths (derived from user-defined variables)
paths:
  exp_name: "exp9"
  proj_path: "/home/mcogo/scratch"
  src_path: "$PROJ_PATH/src"
  xbd_path: "$PROJ_PATH/data"
  exp_path: "$PROJ_PATH/$EXP_NAME"
  data_path: "$EXP_PATH/data"
  out_path: "$EXP_PATH/out"
  
jobs:
  - job_name: "pre"
    conf_num: NULL
    file_list:
     - "$SRC_PATH/run_preprocessing.py"
  - job_name: "final"
    conf_num: NULL
    file_list:
      - "$SRC_PATH/run_final_traning.py"
  - job_name: "post"
    conf_num: NULL
    file_list:
      - "$SRC_PATH/run_postprocessing.py"